In [30]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import scipy
from scipy.stats import norm
import warnings
warnings.filterwarnings('ignore')


In [2]:
import pandas as pd

In [3]:
from arch import arch_model

In [4]:
stock='AXISBANK.NS'
data=yf.download(stock,'2005-01-01','2023-05-05')
data

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close   Adj Close  \
Date                                                                     
2005-01-03   37.000000   38.200001   37.000000   38.040001   32.853157   
2005-01-04   38.220001   38.400002   37.400002   37.939999   32.766777   
2005-01-05   37.990002   37.990002   35.509998   36.849998   31.825399   
2005-01-06   36.820000   38.000000   35.400002   37.029999   31.980864   
2005-01-07   36.130001   38.380001   36.130001   38.020000   32.835873   
...                ...         ...         ...         ...         ...   
2023-04-27  888.000000  890.000000  877.500000  881.400024  879.590454   
2023-04-28  885.099976  890.049988  853.650024  860.000000  858.234375   
2023-05-02  870.000000  876.400024  864.250000  870.650024  868.862549   
2023-05-03  863.849976  866.849976  854.049988  859.849976  858.084717   
2023-05-04  860.000000  867.150024  857.500000  865.950012  864.172180   

              Volume  
Date                  
2005-01-03   1421010  
2005-01-04   1115825  
2005-01-05   1163085  
2005-01-06   1192610  
2005-01-07   1530260  
...              ...  
2023-04-27  15992383  
2023-04-28  23004117  
2023-05-02  12947953  
2023-05-03  15103015  
2023-05-04   9756391  

[4525 rows x 6 columns]

In [5]:
returns=np.diff(data['Adj Close'])
returns

array([ -0.08638   ,  -0.94137764,   0.15546417, ...,  10.62817383,
       -10.77783203,   6.08746338])

In [6]:
import torch
import torch.nn as nn

In [7]:
import pandas as pd
import numpy as np
import arch

In [8]:
returns.shape

(4524,)

In [25]:
def garchquantile(returns):
  # Define the GARCH model
  garch_model = arch.arch_model(returns, vol='Garch', p=1, q=1)

# Fit the GARCH model
  garch_result = garch_model.fit(disp='off')

# Generate the GARCH volatility forecasts
  garch_forecasts = garch_result.forecast(start=0)

# Extract the conditional volatility at the last observation
  forecasted_volatility = np.sqrt(garch_forecasts.variance.values[-1])

# Calculate VaR for the 95th quantile
  confidence_level = 0.05  # 95% confidence level
  z_score = norm.ppf(confidence_level)
  VaR = -z_score * forecasted_volatility
  return VaR

In [26]:
predictions=np.zeros(453)
for i in range(453):
  predictions[i]=(garchquantile(returns[0:4071+i]))
predictions



C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. T

C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. T

C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. T

C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. T

C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  warnings.warn(
C:\Users\momoy\AppData\Local\Programs\Python\Python311\Lib\site-packages\arch\univariate\base.py:766: ConvergenceWarning: The optimizer returned code 8. T

array([16.25662995, 15.82035862, 15.47004249, 15.39729963, 15.22320222,
       15.01312373, 15.98249555, 15.54288796, 15.18475966, 14.7991995 ,
       15.67400933, 15.67849586, 15.24636931, 15.17993399, 14.75726589,
       17.20971577, 17.08301222, 16.76192812, 16.62277228, 16.81328203,
       17.638393  , 18.09111305, 17.68104103, 17.51137178, 17.90350481,
       17.55850852, 17.08116989, 16.66902686, 16.24078857, 15.81496243,
       15.51333569, 15.11830295, 15.69533541, 15.3436591 , 15.41907674,
       15.26136814, 15.08810846, 14.84929672, 18.77133409, 18.28205525,
       18.38666285, 17.94583428, 17.54740999, 17.10750915, 17.3644276 ,
       17.08810339, 16.7185758 , 16.28124628, 15.99711341, 15.6091608 ,
       15.75979057, 15.42624068, 15.65015562, 15.22461516, 15.06040318,
       17.18428127, 17.57188218, 17.09969622, 16.90485836, 16.67368583,
       17.28646751, 16.83159187, 16.87101536, 16.46497922, 16.08866654,
       15.66938584, 15.35024927, 15.05640246, 15.12194698, 14.74

In [27]:
ans=returns[4071:]
ans.shape

(453,)

In [28]:
error=predictions+ans
error

array([ 14.26377106,  20.35411106,   7.000438  ,   8.37245832,
        21.45086335,  32.10192988,  15.28498579,  19.62827614,
        12.19544082,  -1.09380587,   6.25768853,  16.67495582,
        23.8654489 ,  16.07672354,  -9.75488011,   8.44110005,
        11.45319045,   8.44179873,  28.82901007,  34.2009163 ,
        32.78414495,  13.60722633,   9.26118019,  32.10908907,
        23.93188616,  16.81119406,  13.64342575,  19.20998145,
        18.33325684,  10.58370022,  13.17178296,   1.01881565,
        11.56014253,  25.557038  ,   8.14521199,  22.53523289,
        21.11655084,  46.38628402,  21.21255724,  30.63789021,
        22.1730398 ,  13.26260674,  20.33744906,   4.20370055,
        24.18998913,  12.55435095,  14.92493567,  22.3097497 ,
        13.00779456,  26.76913395,  20.49288384,   3.96731734,
        15.15186461,   8.24957854,  38.77549108,   3.13459866,
        16.47581284,   9.37734514,   9.88013912,   1.12931327,
        18.88076683,  27.64281013,  20.45811252,  12.82

In [29]:
loss=0.0
for i in range(error.shape[0]):
  if(error[i]<0):
    loss=loss+-1*0.95*error[i]
  else:
    loss=loss+(1)*error[i]*(0.05)
loss/error.shape[0]

1.4079014122786602