In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'numpy'

In [8]:
import scipy
from scipy.stats import norm

In [9]:
stock='AXISBANK.NS'
data = yf.download(stock,'2005-01-01','2023-05-05')

[*********************100%***********************]  1 of 1 completed


In [10]:
data

Open        High         Low       Close   Adj Close  \
Date                                                                     
2005-01-03   37.000000   38.200001   37.000000   38.040001   32.853138   
2005-01-04   38.220001   38.400002   37.400002   37.939999   32.766777   
2005-01-05   37.990002   37.990002   35.509998   36.849998   31.825401   
2005-01-06   36.820000   38.000000   35.400002   37.029999   31.980856   
2005-01-07   36.130001   38.380001   36.130001   38.020000   32.835869   
...                ...         ...         ...         ...         ...   
2023-04-27  888.000000  890.000000  877.500000  881.400024  879.590454   
2023-04-28  885.099976  890.049988  853.650024  860.000000  858.234375   
2023-05-02  870.000000  876.400024  864.250000  870.650024  868.862549   
2023-05-03  863.849976  866.849976  854.049988  859.849976  858.084717   
2023-05-04  860.000000  867.150024  857.500000  865.950012  864.172180   

              Volume  
Date                  
2005-01-03   1421010  
2005-01-04   1115825  
2005-01-05   1163085  
2005-01-06   1192610  
2005-01-07   1530260  
...              ...  
2023-04-27  15992383  
2023-04-28  23004117  
2023-05-02  12947953  
2023-05-03  15103015  
2023-05-04   9756391  

[4525 rows x 6 columns]

In [11]:
# data = data[:4000]

In [12]:
returns = np.diff(data['Adj Close'])
returns=-returns

In [13]:
data.shape,returns.shape

((4525, 6), (4524,))

In [14]:
returns.shape

(4524,)

In [15]:
np.sum(returns)

-831.3190422058105

In [16]:
data['Adj Close']

Date
2005-01-03     32.853138
2005-01-04     32.766777
2005-01-05     31.825401
2005-01-06     31.980856
2005-01-07     32.835869
                 ...    
2023-04-27    879.590454
2023-04-28    858.234375
2023-05-02    868.862549
2023-05-03    858.084717
2023-05-04    864.172180
Name: Adj Close, Length: 4525, dtype: float64

In [17]:
mean = np.mean(returns)
std_dev = np.std(returns)
mean,std_dev

(-0.1837575248023454, 8.99149676480316)

In [18]:
np.array(returns)

array([  0.08636093,   0.94137573,  -0.15545464, ..., -10.62817383,
        10.77783203,  -6.08746338])

In [19]:
np.sort(np.array(returns))

array([-77.87475586, -74.39697266, -63.17364502, ...,  59.98513794,
        75.82830811, 119.07345581])

In [20]:
import torch
import torch.nn as nn
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

In [21]:
def quantile_loss(q, y, y_p):
        e = y-y_p
        return tf.keras.backend.mean(tf.keras.backend.maximum(q*e, (q-1)*e))


In [22]:
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, activation='relu', input_dim=1))
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='linear'))

In [23]:
quantile = 0.95
model.compile(optimizer='adam', loss=lambda y, y_p: quantile_loss(quantile, y, y_p))

In [26]:
input=data['Adj Close'][0:-1]
input.shape,returns.shape

((4524,), (4524,))

In [28]:
model.fit(input,returns,epochs=1000)

Epoch 1/20
142/142 [==============================] - 1s 2ms/step - loss: 0.9814
Epoch 2/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9726
Epoch 3/20
142/142 [==============================] - 0s 2ms/step - loss: 1.0013
Epoch 4/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9665
Epoch 5/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9501
Epoch 6/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9450
Epoch 7/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9562
Epoch 8/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9302
Epoch 9/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9323
Epoch 10/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9467
Epoch 11/20
142/142 [==============================] - 0s 2ms/step - loss: 0.9388
Epoch 12/20
142/142 [==============================] - 0s 3ms/step - loss: 0.9458
Epoch 13/20
142/142 [====

In [29]:
pred=model.predict(input[4071:])
loss=quantile_loss(0.95,returns[4071:],pred)
loss

15/15 [==============================] - 0s 3ms/step


<tf.Tensor: shape=(), dtype=float64, numpy=1.81250702749535>